import { PerkId } from "./types";

export const synergies: Partial<Record<PerkId, Array<PerkId>>> = {
  streak_shots: ["puck_repulse_ball", "wrap_up"],
  left_is_lava: ["concave_puck", "telekinesis", "yoyo"],
  right_is_lava: ["concave_puck", "telekinesis", "yoyo"],
  top_is_lava: ["flyswatter"],
  picky_eater: ["pierce_color", "soft_brush"],
  compound_interest: ["viscosity", "coin_magnet", "bigger_puck"],
  hot_start: ["pierce", "sapper", "bigger_explosions", "refill", "multiball"],
  asceticism: [
    "bricks_attract_coins",
    "helium",
    "sticky_coins",
    "sapper",
    "trickledown",
  ],
  nbricks: ["ottawa_treaty", "flyswatter", "soft_touch"],
  zen: ["ottawa_treaty"],
  trampoline: ["concave_puck", "telekinesis", "yoyo"],
  reach: [
    "telekinesis",
    "concave_puck",
    "corner_shot",
    "refill",
    "soft_touch",
    "limitless",
    "round_bricks",
    "hardhat",
  ],
  passive_income: [
    "yoyo",
    "viscosity",
    "bricks_attract_coins",
    "buoy",
    "pierce_above_paddle",
  ],
  side_kick: ["wrap_right", "pierce_left", "refill"],
  side_flip: ["wrap_left", "pierce_right", "refill"],
  addiction: ["bricks_attract_ball", "pierce", "multiball", "skip_last"],
  three_cushion: ["wind"],
  happy_family: ["yoyo", "bigger_puck", "telekinesis", "soft_touch"],
  palette: ["disco_ball", "metamorphosis", "rainbow"],
  paddle_up_combo: ["pierce_above_paddle", "soft_touch"],
  varied_diet: ["metamorphosis", "disco_ball"],
  extra_levels: ["limitless"],
  sacrifice: ["extra_life"],
  vibrant_neighborhood: ["fumes", "metamorphosis", "rainbow", "telekinesis"],
  // beginner helpers
  slow_down: [
    "base_combo",
    "bigger_puck",
    "extra_life",
    "telekinesis",
    "yoyo",
    "skip_last",
    "chill",
  ],
  // hardcore players
  smaller_puck: ["double_or_nothing", "limitless"],
};
