import { t } from "./i18n/i18n";

import { PerkId } from "./types";

import {
  base_combo_from_stronger_foundation,
  comboKeepingRate,
} from "./pure_functions";

export const noCreative: PerkId[] = [
  "extra_levels",
  "shunt",
  "one_more_choice",
  "chill",
];

export const categories = {
  combo: 1,
  beginner: 2,
  combo_boost: 3,
  simple: 4,
  pierce: 5,
  advanced: 6,
};

export const rawUpgrades = [
  {
    category: categories.combo,
    requires: [],
    threshold: 390000,
    id: "varied_diet",
    max: 3,
    hardLimit: 9,
    name: t("upgrades.varied_diet.name"),
    help: (lvl: number) =>
      t("upgrades.varied_diet.tooltip", { plus: lvl, minus: lvl * 2 }),
    fullHelp: (lvl: number) =>
      t("upgrades.varied_diet.verbose_description", {
        plus: lvl,
        minus: lvl * 2,
      }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 0,
    id: "streak_shots",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.streak_shots.name"),
    help: (lvl: number) => t("upgrades.streak_shots.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.streak_shots.verbose_description", { lvl }),
  },

  {
    category: categories.combo,
    requires: [],
    threshold: 200,
    id: "left_is_lava",
    max: 1,
    hardLimit: 2,
    name: t("upgrades.left_is_lava.name"),
    help: (lvl: number) => t("upgrades.left_is_lava.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.left_is_lava.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 300,
    id: "right_is_lava",
    max: 1,
    hardLimit: 2,
    name: t("upgrades.right_is_lava.name"),
    help: (lvl: number) => t("upgrades.right_is_lava.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.right_is_lava.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 400,
    id: "top_is_lava",
    max: 1,
    hardLimit: 2,
    name: t("upgrades.top_is_lava.name"),
    help: (lvl: number) => t("upgrades.top_is_lava.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.top_is_lava.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 4000,
    id: "hot_start",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.hot_start.name"),
    help: (lvl: number) =>
      t("upgrades.hot_start.tooltip", {
        start: lvl * 30 + 1,
        loss: lvl,
      }),
    fullHelp: (lvl: number) =>
      t("upgrades.hot_start.verbose_description", {
        start: lvl * 30 + 1,
        loss: lvl,
      }),
  },

  {
    category: categories.combo,
    requires: [],
    threshold: 2000,
    id: "picky_eater",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.picky_eater.name"),
    help: (lvl: number) => t("upgrades.picky_eater.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.picky_eater.verbose_description", { lvl }),
  },

  {
    category: categories.combo,
    requires: [],
    threshold: 3000,
    id: "compound_interest",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.compound_interest.name"),
    help: (lvl: number) => t("upgrades.compound_interest.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.compound_interest.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 150000,
    id: "side_kick",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.side_kick.name"),
    help: (lvl: number) =>
      t("upgrades.side_kick.tooltip", { lvl, loss: lvl * 2 }),
    fullHelp: (lvl: number) =>
      t("upgrades.side_kick.verbose_description", { lvl, loss: lvl * 2 }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 150000,
    id: "side_flip",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.side_flip.name"),
    help: (lvl: number) =>
      t("upgrades.side_flip.tooltip", { lvl, loss: lvl * 2 }),
    fullHelp: (lvl: number) =>
      t("upgrades.side_flip.verbose_description", { lvl, loss: lvl * 2 }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 135000,
    id: "reach",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.reach.name"),
    help: (lvl: number) => t("upgrades.reach.tooltip", { lvl }),
    fullHelp: (lvl: number) => t("upgrades.reach.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: ["multiball"],
    threshold: 245000,
    id: "happy_family",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.happy_family.name"),
    help: () => t("upgrades.happy_family.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.happy_family.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 165000,
    id: "addiction",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.addiction.name"),
    help: (lvl: number) =>
      t("upgrades.addiction.tooltip", { lvl, delay: (5 / lvl).toFixed(2) }),
    fullHelp: (lvl: number) =>
      t("upgrades.addiction.verbose_description", {
        lvl,
        delay: (5 / lvl).toFixed(2),
      }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 90000,
    id: "nbricks",
    max: 3,
    hardLimit: 6,
    name: t("upgrades.nbricks.name"),
    help: (lvl: number) => t("upgrades.nbricks.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.nbricks.verbose_description", {
        gain: lvl * 2,
        max: lvl * 2,
      }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 230000,
    id: "three_cushion",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.three_cushion.name"),
    help: (lvl: number) =>
      t("upgrades.three_cushion.tooltip", { max: lvl * 3 }),
    fullHelp: (lvl: number) =>
      t("upgrades.three_cushion.verbose_description", { max: lvl * 3 }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 115000,
    id: "trampoline",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.trampoline.name"),
    help: (lvl: number) => t("upgrades.trampoline.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.trampoline.verbose_description", { lvl }),
  },

  {
    category: categories.combo,
    requires: [],
    threshold: 105000,
    id: "zen",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.zen.name"),
    help: (lvl: number) => t("upgrades.zen.tooltip", { lvl }),
    fullHelp: (lvl: number) => t("upgrades.zen.verbose_description", { lvl }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 70000,
    id: "asceticism",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.asceticism.name"),
    help: (lvl: number) =>
      t("upgrades.asceticism.tooltip", { combo: lvl * 3, loss: lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.asceticism.verbose_description", {
        combo: lvl * 3,
        loss: lvl,
      }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 140000,
    id: "passive_income",
    max: 4,
    hardLimit: Infinity,
    name: t("upgrades.passive_income.name"),
    help: (lvl: number) =>
      t("upgrades.passive_income.tooltip", {
        time: (lvl * 0.1 - 0.05).toFixed(2),
        lvl,
      }),
    fullHelp: (lvl: number) =>
      t("upgrades.passive_income.verbose_description", {
        time: (lvl * 0.1 - 0.05).toFixed(2),
        lvl,
      }),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 275000,
    id: "palette",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.palette.name"),
    help: (lvl: number) => t("upgrades.palette.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.palette.verbose_description"),
  },
  {
    category: categories.combo,
    requires: [],
    threshold: 290000,
    id: "paddle_up_combo",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.paddle_up_combo.name"),
    help: (lvl: number) => t("upgrades.paddle_up_combo.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.paddle_up_combo.verbose_description"),
  },

  {
    category: categories.beginner,
    // so that you get the starting base combo perk
    requires: ["base_combo"],
    threshold: 0,
    id: "slow_down",
    max: 2,
    hardLimit: Infinity,
    name: t("upgrades.slow_down.name"),
    help: (lvl: number) => t("upgrades.slow_down.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.slow_down.verbose_description", { lvl }),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 0,
    id: "extra_life",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.extra_life.name"),
    help: (lvl: number) => t("upgrades.extra_life.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.extra_life.verbose_description", { lvl }),
  },

  {
    category: categories.beginner,
    requires: [],
    threshold: 0,
    id: "bigger_puck",
    max: 2,
    hardLimit: Infinity,
    name: t("upgrades.bigger_puck.name"),
    help: () => t("upgrades.bigger_puck.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.bigger_puck.verbose_description", { lvl }),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 5000,
    id: "bigger_balls",
    max: 2,
    hardLimit: 8,
    name: t("upgrades.bigger_balls.name"),
    help: (lvl: number) => t("upgrades.bigger_balls.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.bigger_balls.verbose_description"),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 50,
    id: "skip_last",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.skip_last.name"),
    help: (lvl: number) => t("upgrades.skip_last.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.skip_last.verbose_description", { lvl }),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 500,
    id: "telekinesis",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.telekinesis.name"),
    help: (lvl: number) => t("upgrades.telekinesis.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.telekinesis.verbose_description", { lvl }),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 600,
    id: "yoyo",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.yoyo.name"),
    help: (lvl: number) => t("upgrades.yoyo.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.yoyo.verbose_description", { lvl }),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 750,
    id: "one_more_choice",
    max: 3,
    hardLimit: 6,
    name: t("upgrades.one_more_choice.name"),
    help: (lvl: number) => t("upgrades.one_more_choice.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.one_more_choice.verbose_description", { lvl }),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 950,
    id: "concave_puck",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.concave_puck.name"),
    help: (lvl: number) => t("upgrades.concave_puck.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.concave_puck.verbose_description", { lvl }),
  },

  {
    category: categories.pierce,
    requires: [],
    threshold: 15000,
    id: "pierce_color",
    max: 4,
    hardLimit: Infinity,
    name: t("upgrades.pierce_color.name"),
    help: (lvl: number) => t("upgrades.pierce_color.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.pierce_color.verbose_description", { lvl }),
  },
  {
    category: categories.pierce,
    requires: [],
    threshold: 1500,
    id: "pierce",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.pierce.name"),
    help: (lvl: number) => t("upgrades.pierce.tooltip", { count: lvl * 2 }),
    fullHelp: (lvl: number) =>
      t("upgrades.pierce.verbose_description", { count: lvl * 2 }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 800,
    id: "multiball",
    max: 6,
    hardLimit: Infinity,
    name: t("upgrades.multiball.name"),
    help: (lvl: number) => t("upgrades.multiball.tooltip", { count: lvl + 1 }),
    fullHelp: (lvl: number) =>
      t("upgrades.multiball.verbose_description", { count: lvl + 1 }),
  },
  {
    category: categories.advanced,
    requires: ["multiball"],
    threshold: 21000,
    id: "ball_repulse_ball",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.ball_repulse_ball.name"),
    help: (lvl: number) => t("upgrades.ball_repulse_ball.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.ball_repulse_ball.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: ["multiball"],
    threshold: 25000,
    id: "ball_attract_ball",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.ball_attract_ball.name"),
    help: (lvl: number) => t("upgrades.ball_attract_ball.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.ball_attract_ball.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 30000,
    id: "puck_repulse_ball",
    max: 2,
    hardLimit: Infinity,
    name: t("upgrades.puck_repulse_ball.name"),
    help: (lvl: number) => t("upgrades.puck_repulse_ball.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.puck_repulse_ball.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 35000,
    id: "wind",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.wind.name"),
    help: (lvl: number) => t("upgrades.wind.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.wind.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 65000,
    id: "helium",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.helium.name"),
    help: (lvl: number) => t("upgrades.helium.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.helium.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 200000,
    id: "bricks_attract_coins",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.bricks_attract_coins.name"),
    help: (lvl: number) => t("upgrades.bricks_attract_coins.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.bricks_attract_coins.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 240000,
    id: "wrap_left",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.wrap_left.name"),
    help: () => t("upgrades.wrap_left.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.wrap_left.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 245000,
    id: "wrap_right",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.wrap_right.name"),
    help: () => t("upgrades.wrap_right.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.wrap_right.verbose_description", { lvl }),
  },

  {
    category: categories.simple,
    requires: [],
    threshold: 45000,
    id: "respawn",
    max: 4,
    hardLimit: Infinity,
    name: t("upgrades.respawn.name"),
    help: (lvl: number) =>
      t("upgrades.respawn.tooltip", {
        percent: Math.floor(100 * comboKeepingRate(lvl)),
        delay: (3 / lvl).toFixed(2),
      }),
    fullHelp: (lvl: number) =>
      t("upgrades.respawn.verbose_description", {
        percent: Math.floor(100 * comboKeepingRate(lvl)),
        delay: (3 / lvl).toFixed(2),
      }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 55000,
    id: "double_or_nothing",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.double_or_nothing.name"),
    help: (lvl: number) => t("upgrades.double_or_nothing.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.double_or_nothing.verbose_description"),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 75000,
    id: "unbounded",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.unbounded.name"),
    help: (lvl: number) => t("upgrades.unbounded.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.unbounded.verbose_description", { lvl }),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 95000,
    id: "etherealcoins",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.etherealcoins.name"),
    help: (lvl: number) => t("upgrades.etherealcoins.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.etherealcoins.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: ["multiball"],
    threshold: 100000,
    id: "shocks",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.shocks.name"),
    help: (lvl: number) => t("upgrades.shocks.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.shocks.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: ["extra_life"],
    threshold: 110000,
    id: "sacrifice",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.sacrifice.name"),
    help: (lvl: number) => t("upgrades.sacrifice.tooltip", { gain: 100 * lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.sacrifice.verbose_description", { gain: 100 * lvl }),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 120000,
    id: "ghost_coins",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.ghost_coins.name"),
    help: (lvl: number) => t("upgrades.ghost_coins.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.ghost_coins.verbose_description", { lvl }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 125000,
    id: "forgiving",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.forgiving.name"),
    help: (lvl: number) => t("upgrades.forgiving.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.forgiving.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 130000,
    id: "ball_attracts_coins",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.ball_attracts_coins.name"),
    help: (lvl: number) => t("upgrades.ball_attracts_coins.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.ball_attracts_coins.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 145000,
    id: "clairvoyant",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.clairvoyant.name"),
    help: (lvl: number) => t("upgrades.clairvoyant.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.clairvoyant.verbose_description", { lvl }),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 155000,
    id: "implosions",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.implosions.name"),
    help: (lvl: number) => t("upgrades.implosions.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.implosions.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 160000,
    id: "corner_shot",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.corner_shot.name"),
    help: (lvl: number) => t("upgrades.corner_shot.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.corner_shot.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 175000,
    id: "limitless",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.limitless.name"),
    help: (lvl: number) => t("upgrades.limitless.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.limitless.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 185000,
    id: "trickledown",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.trickledown.name"),
    help: (lvl: number) => t("upgrades.trickledown.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.trickledown.verbose_description", { lvl }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 190000,
    id: "transparency",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.transparency.name"),
    help: (lvl: number) =>
      t("upgrades.transparency.tooltip", { lvl, percent: lvl * 50 }),
    fullHelp: (lvl: number) =>
      t("upgrades.transparency.verbose_description", {
        lvl,
        percent: lvl * 50,
      }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 195000,
    id: "superhot",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.superhot.name"),
    help: (lvl: number) => t("upgrades.superhot.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.superhot.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 205000,
    id: "rainbow",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.rainbow.name"),
    help: (lvl: number) => t("upgrades.rainbow.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.rainbow.verbose_description", { lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 208000,
    id: "disco_ball",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.disco_ball.name"),
    help: () => t("upgrades.disco_ball.tooltip"),
    fullHelp: () => t("upgrades.disco_ball.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 210000,
    id: "golden_goose",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.golden_goose.name"),
    help: (lvl: number) => t("upgrades.golden_goose.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.golden_goose.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 215000,
    id: "bricks_attract_ball",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.bricks_attract_ball.name"),
    help: (lvl: number) =>
      t("upgrades.bricks_attract_ball.tooltip", { count: lvl * 3 }),
    fullHelp: (lvl: number) =>
      t("upgrades.bricks_attract_ball.verbose_description", { count: lvl * 3 }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 220000,
    id: "buoy",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.buoy.name"),
    help: (lvl: number) => t("upgrades.buoy.tooltip", { duration: lvl * 0.5 }),
    fullHelp: (lvl: number) =>
      t("upgrades.buoy.verbose_description", { duration: lvl * 0.5 }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 225000,
    id: "ottawa_treaty",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.ottawa_treaty.name"),
    help: () => t("upgrades.ottawa_treaty.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.ottawa_treaty.verbose_description", { lvl }),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 235000,
    id: "sticky_coins",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.sticky_coins.name"),
    help: (lvl: number) => t("upgrades.sticky_coins.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.sticky_coins.verbose_description", { lvl }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 0,
    id: "base_combo",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.base_combo.name"),
    help: (lvl: number) =>
      t("upgrades.base_combo.tooltip", {
        coins: base_combo_from_stronger_foundation(lvl),
      }),
    fullHelp: (lvl: number) =>
      t("upgrades.base_combo.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 0,
    id: "viscosity",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.viscosity.name"),
    help: () => t("upgrades.viscosity.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.viscosity.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 700,
    id: "coin_magnet",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.coin_magnet.name"),
    help: (lvl: number) => t("upgrades.coin_magnet.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.coin_magnet.verbose_description", { lvl }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 1000,
    id: "smaller_puck",
    max: 2,
    hardLimit: Infinity,
    name: t("upgrades.smaller_puck.name"),
    help: (lvl: number) =>
      t("upgrades.smaller_puck.tooltip", { percent: 50 * lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.smaller_puck.verbose_description", { percent: 50 * lvl }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 2500,
    id: "metamorphosis",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.metamorphosis.name"),
    help: (lvl: number) => t("upgrades.metamorphosis.tooltip", { lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.metamorphosis.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 6000,
    id: "sapper",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.sapper.name"),
    help: (lvl: number) => t("upgrades.sapper.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.sapper.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 9000,
    id: "bigger_explosions",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.bigger_explosions.name"),
    help: (lvl: number) => t("upgrades.bigger_explosions.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.bigger_explosions.verbose_description", { lvl }),
  },
  {
    category: categories.simple,
    requires: [],
    threshold: 13000,
    adventure: false,
    id: "extra_levels",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.extra_levels.name"),
    help: (lvl: number) =>
      t("upgrades.extra_levels.tooltip", { count: lvl + 7 }),
    fullHelp: (lvl: number) => t("upgrades.extra_levels.verbose_description"),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 170000,
    id: "fountain_toss",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.fountain_toss.name"),
    help: () => t("upgrades.fountain_toss.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.fountain_toss.verbose_description", { lvl }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 180000,
    id: "minefield",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.minefield.name"),
    help: (lvl: number) =>
      t("upgrades.minefield.tooltip", { percent: 10 * lvl }),
    fullHelp: (lvl: number) =>
      t("upgrades.minefield.verbose_description", { percent: 10 * lvl }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 18000,
    id: "soft_reset",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.soft_reset.name"),
    help: (lvl: number) =>
      t("upgrades.soft_reset.tooltip", {
        percent: Math.round(comboKeepingRate(lvl) * 100),
      }),
    fullHelp: (lvl: number) =>
      t("upgrades.soft_reset.verbose_description", {
        percent: Math.round(comboKeepingRate(lvl) * 100),
      }),
  },
  {
    category: categories.combo_boost,
    requires: [],
    threshold: 80000,
    id: "shunt",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.shunt.name"),
    help: (lvl: number) =>
      t("upgrades.shunt.tooltip", {
        percent: Math.round(comboKeepingRate(lvl) * 100),
      }),
    fullHelp: (lvl: number) =>
      t("upgrades.shunt.verbose_description", {
        percent: Math.round(comboKeepingRate(lvl) * 100),
      }),
  },

  {
    category: categories.combo_boost,
    requires: [],
    threshold: 40000,
    id: "sturdy_bricks",
    max: 4,
    hardLimit: Infinity,
    name: t("upgrades.sturdy_bricks.name"),
    help: (lvl: number) =>
      t("upgrades.sturdy_bricks.tooltip", { lvl, percent: lvl * 50 }),
    fullHelp: (lvl: number) =>
      t("upgrades.sturdy_bricks.verbose_description", {
        lvl,
        percent: lvl * 50,
      }),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 250000,
    id: "steering",
    max: 4,
    hardLimit: Infinity,
    name: t("upgrades.steering.name"),
    help: (lvl: number) => t("upgrades.steering.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.steering.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 255000,
    id: "wrap_up",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.wrap_up.name"),
    help: (lvl: number) => t("upgrades.wrap_up.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.wrap_up.verbose_description"),
  },
  {
    category: categories.beginner,
    requires: [],
    threshold: 5000,
    id: "chill",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.chill.name"),
    help: (lvl: number) => t("upgrades.chill.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.chill.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 260000,
    id: "round_bricks",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.round_bricks.name"),
    help: (lvl: number) => t("upgrades.round_bricks.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.round_bricks.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: ["multiball"],
    threshold: 265000,
    id: "thomas",
    max: 1,
    hardLimit: Infinity,
    name: t("upgrades.thomas.name"),
    help: (lvl: number) => t("upgrades.thomas.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.thomas.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 270000,
    id: "flyswatter",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.flyswatter.name"),
    help: (lvl: number) => t("upgrades.flyswatter.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.flyswatter.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 275000,
    id: "gravity_falls",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.gravity_falls.name"),
    help: (lvl: number) => t("upgrades.gravity_falls.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.gravity_falls.verbose_description"),
  },

  {
    category: categories.combo,
    requires: [],
    threshold: 280000,
    id: "vibrant_neighborhood",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.vibrant_neighborhood.name"),
    help: (lvl: number) => t("upgrades.vibrant_neighborhood.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.vibrant_neighborhood.verbose_description"),
  },

  {
    category: categories.pierce,
    requires: [],
    threshold: 300000,
    id: "pierce_left",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.pierce_left.name"),
    help: (lvl: number) => t("upgrades.pierce_left.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.pierce_left.verbose_description"),
  },
  {
    category: categories.pierce,
    requires: [],
    threshold: 310000,
    id: "pierce_right",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.pierce_right.name"),
    help: (lvl: number) => t("upgrades.pierce_right.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.pierce_right.verbose_description"),
  },
  {
    category: categories.pierce,
    requires: [],
    threshold: 320000,
    id: "pierce_top",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.pierce_top.name"),
    help: (lvl: number) => t("upgrades.pierce_top.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.pierce_top.verbose_description"),
  },
  {
    category: categories.pierce,
    requires: [
      "pierce",
      "pierce_color",
      "pierce_left",
      "pierce_right",
      "pierce_top",
      "pierce_above_paddle",
    ],
    threshold: 330000,
    id: "refill",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.refill.name"),
    help: (lvl: number) => t("upgrades.refill.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.refill.verbose_description"),
  },

  {
    category: categories.pierce,
    requires: [],
    threshold: 370000,
    id: "pierce_above_paddle",
    max: 3,
    hardLimit: Infinity,
    name: t("upgrades.pierce_above_paddle.name"),
    help: (lvl: number) => t("upgrades.pierce_above_paddle.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.pierce_above_paddle.verbose_description"),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 380000,
    id: "soft_touch",
    max: 1,
    hardLimit: 2,
    name: t("upgrades.soft_touch.name"),
    help: (lvl: number) => t("upgrades.soft_touch.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.soft_touch.verbose_description"),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 400000,
    id: "instant_explosion",
    max: 1,
    hardLimit: 1,
    name: t("upgrades.instant_explosion.name"),
    help: (lvl: number) => t("upgrades.instant_explosion.tooltip"),
    fullHelp: (lvl: number) =>
      t("upgrades.instant_explosion.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 410000,
    id: "soft_brush",
    max: 7,
    hardLimit: Infinity,
    name: t("upgrades.soft_brush.name"),
    help: (lvl: number) => t("upgrades.soft_brush.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.soft_brush.verbose_description"),
  },
  {
    category: categories.advanced,
    requires: [],
    threshold: 420000,
    id: "fumes",
    max: 1,
    hardLimit: 2,
    name: t("upgrades.fumes.name"),
    help: (lvl: number) => t("upgrades.fumes.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.fumes.verbose_description"),
  },

  {
    category: categories.advanced,
    requires: [],
    threshold: 430000,
    id: "hardhat",
    max: 1,
    hardLimit: 3,
    name: t("upgrades.hardhat.name"),
    help: (lvl: number) => t("upgrades.hardhat.tooltip"),
    fullHelp: (lvl: number) => t("upgrades.hardhat.verbose_description"),
  },
] as const;
